### ISSUE TITLE
HTTP Error 405: Method Not Allowed

### ISSUE THREAD

**Issue by zlosim** [mistercrunch/panoramix#54]
Hi
I was trying to install panoramix, I installed it following installation guide, added my cluster and hit "Refresh Druid Metadata" button which ended up with IO error
```
2015-10-22 19:16:17,432:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.0.3.54
2015-10-22 19:16:17,437:DEBUG:requests.packages.urllib3.connectionpool:"GET /druid/coordinator/v1/datasources HTTP/1.1" 200 None
2015-10-22 19:16:17,467:INFO:werkzeug:10.0.0.100 - - [22/Oct/2015 19:16:17] "GET /panoramix/refresh_datasources/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/panoramix/views.py", line 411, in refresh_datasources
    cluster.refresh_datasources()
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/panoramix/models.py", line 636, in refresh_datasources
    Datasource.sync_to_db(datasource, self)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/panoramix/models.py", line 718, in sync_to_db
    cols = datasource.latest_metadata()
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/panoramix/models.py", line 692, in latest_metadata
    results = client.time_boundary(datasource=self.datasource_name)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/pydruid/client.py", line 550, in time_boundary
    return self.__post(self.query_dict)
  File "/home/mvince/.virtualenvs/druid/lib/python2.7/site-packages/pydruid/client.py", line 137, in __post
    e, err,json.dumps(self.query_dict, indent=4)))
IOError: HTTP Error 405: Method Not Allowed 
 Druid Error: None 
 Query is: {
    "queryType": "timeBoundary", 
    "dataSource": "DAU_v1"
}
```
Do I need to set some other permissions? 

I`m using druid 0.8.1 and python 2.7.3
also curling coordinator endpoint works as expected
```
t 22 17:30:55 2015 from 92.240.230.58
$ curl -XGET '{coordinator_host}:8081/druid/coordinator/v1/datasources' 
["DAU_v1","registrations_v1"]
```

**Comment by zlosim** [comment]
bad endpoint for broker node, should be
```
{broker_host}:8082/druid/v2
```
